# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='arm_armour_awarded',
        ),
        migrations.RemoveField(
            model_name='event',
            name='backpack_awarded',
        ),
        migrations.RemoveField(
            model_name='event',
            name='battle_item_awarded',
        ),
        migrations.RemoveField(
            model_name='event',
            name='body_armour_awarded',
        ),
        migrations.RemoveField(
            model_name='event',
            name='head_armour_awarded',
        ),
        migrations.RemoveField(
            model_name='event',
            name='leg_armour_awarded',
        ),
        migrations.RemoveField(
            model_name='event',
            name='player_event_awarded',
        ),
        migrations.RemoveField(
            model_name='event',
            name='shield_item_awarded',
        ),
        migrations.AddField(
            model_name='event',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='event',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
