# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmArmour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount_of_items', models.DecimalField(decimal_places=0, max_digits=2)),
                ('health', models.DecimalField(decimal_places=0, max_digits=2)),
                ('value', models.DecimalField(decimal_places=0, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount_of_items', models.DecimalField(decimal_places=0, max_digits=2)),
                ('health', models.DecimalField(decimal_places=0, max_digits=2)),
                ('value', models.DecimalField(decimal_places=0, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BattleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BodyArmour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount_of_items', models.DecimalField(decimal_places=0, max_digits=2)),
                ('health', models.DecimalField(decimal_places=0, max_digits=2)),
                ('value', models.DecimalField(decimal_places=0, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount_of_items', models.DecimalField(decimal_places=0, max_digits=2)),
                ('health', models.DecimalField(decimal_places=0, max_digits=2)),
                ('value', models.DecimalField(decimal_places=0, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LegArmour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount_of_items', models.DecimalField(decimal_places=0, max_digits=2)),
                ('health', models.DecimalField(decimal_places=0, max_digits=2)),
                ('value', models.DecimalField(decimal_places=0, max_digits=7)),
                ('item', models.ManyToManyField(to='player.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('coordination', models.DecimalField(decimal_places=0, max_digits=2)),
                ('luck', models.DecimalField(decimal_places=0, max_digits=2)),
                ('awareness', models.DecimalField(decimal_places=0, max_digits=2)),
                ('strength', models.DecimalField(decimal_places=0, max_digits=2)),
                ('speed', models.DecimalField(decimal_places=0, max_digits=2)),
                ('intelligent', models.DecimalField(decimal_places=0, max_digits=2)),
                ('charisma', models.DecimalField(decimal_places=0, max_digits=2)),
                ('health', models.DecimalField(decimal_places=0, max_digits=2)),
                ('lives', models.DecimalField(decimal_places=0, max_digits=2)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('backpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.BackPack')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.BodyArmour')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Faction')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Head')),
                ('left_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_arm', to='player.ArmArmour')),
                ('left_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_leg', to='player.LegArmour')),
                ('right_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_arm', to='player.ArmArmour')),
                ('right_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_leg', to='player.LegArmour')),
            ],
        ),
        migrations.AddField(
            model_name='head',
            name='item',
            field=models.ManyToManyField(to='player.Item'),
        ),
        migrations.AddField(
            model_name='bodyarmour',
            name='item',
            field=models.ManyToManyField(to='player.Item'),
        ),
        migrations.AddField(
            model_name='backpack',
            name='item',
            field=models.ManyToManyField(to='player.Item'),
        ),
        migrations.AddField(
            model_name='armarmour',
            name='battle_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.BattleItem'),
        ),
        migrations.AddField(
            model_name='armarmour',
            name='item',
            field=models.ManyToManyField(to='player.Item'),
        ),
    ]
