# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='awareness',
        ),
        migrations.RemoveField(
            model_name='player',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='player',
            name='coordination',
        ),
        migrations.RemoveField(
            model_name='player',
            name='intelligent',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lives',
        ),
        migrations.RemoveField(
            model_name='player',
            name='luck',
        ),
        migrations.RemoveField(
            model_name='player',
            name='speed',
        ),
        migrations.AddField(
            model_name='player',
            name='attacks',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='ballistic',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='initiative',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='leadership',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='melee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='toughness',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='wounds',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='health',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='strength',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
