# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20161008_1150'),
        ('armour', '0003_auto_20161008_1150'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='backpack',
            new_name='equipped_backpack',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='body',
            new_name='equipped_body_armour',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='head',
            new_name='equipped_head_armour',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='left_leg',
            new_name='equipped_left_leg_armour',
        ),
        migrations.RemoveField(
            model_name='player',
            name='left_arm',
        ),
        migrations.RemoveField(
            model_name='player',
            name='right_arm',
        ),
        migrations.RemoveField(
            model_name='player',
            name='right_leg',
        ),
        migrations.AddField(
            model_name='player',
            name='equipped_battle_item',
            field=models.ManyToManyField(blank=True, to='item.BattleItem'),
        ),
        migrations.AddField(
            model_name='player',
            name='equipped_left_arm_armour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_arm', to='armour.ArmArmour'),
        ),
        migrations.AddField(
            model_name='player',
            name='equipped_right_arm_armour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_arm', to='armour.ArmArmour'),
        ),
        migrations.AddField(
            model_name='player',
            name='equipped_right_leg_armour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_leg', to='armour.LegArmour'),
        ),
        migrations.AddField(
            model_name='player',
            name='equipped_shield_item',
            field=models.ManyToManyField(blank=True, to='item.ShieldItem'),
        ),
    ]
