# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20161008_1150'),
        ('player', '0002_auto_20161008_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='equipped_battle_item',
        ),
        migrations.AddField(
            model_name='player',
            name='equipped_battle_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.BattleItem'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='equipped_shield_item',
        ),
        migrations.AddField(
            model_name='player',
            name='equipped_shield_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.ShieldItem'),
        ),
    ]
