# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-10 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('player', '0003_auto_20161008_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_event_directory',
            field=models.ManyToManyField(blank=True, to='event.PlayerEventDirectory'),
        ),
    ]
