# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20160824_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='user',
            new_name='account',
        ),
    ]
