# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20160824_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armarmour',
            name='item',
            field=models.ManyToManyField(blank=True, to='player.Item'),
        ),
        migrations.AlterField(
            model_name='backpack',
            name='item',
            field=models.ManyToManyField(blank=True, to='player.Item'),
        ),
        migrations.AlterField(
            model_name='bodyarmour',
            name='item',
            field=models.ManyToManyField(blank=True, to='player.Item'),
        ),
        migrations.AlterField(
            model_name='head',
            name='item',
            field=models.ManyToManyField(blank=True, to='player.Item'),
        ),
        migrations.AlterField(
            model_name='legarmour',
            name='item',
            field=models.ManyToManyField(blank=True, to='player.Item'),
        ),
    ]
