# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20160825_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='backpack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.BackPack'),
        ),
        migrations.AlterField(
            model_name='player',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.BodyArmour'),
        ),
        migrations.AlterField(
            model_name='player',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Faction'),
        ),
        migrations.AlterField(
            model_name='player',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Head'),
        ),
        migrations.AlterField(
            model_name='player',
            name='left_arm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_arm', to='player.ArmArmour'),
        ),
        migrations.AlterField(
            model_name='player',
            name='left_leg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_leg', to='player.LegArmour'),
        ),
        migrations.AlterField(
            model_name='player',
            name='right_arm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_arm', to='player.ArmArmour'),
        ),
        migrations.AlterField(
            model_name='player',
            name='right_leg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_leg', to='player.LegArmour'),
        ),
    ]
