# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShieldItem',
            fields=[
                ('standarditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.StandardItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('item.standarditem',),
        ),
        migrations.RemoveField(
            model_name='battleitem',
            name='created',
        ),
        migrations.RemoveField(
            model_name='battleitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='battleitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='battleitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='battleitem',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='battleitem',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='battleitem',
            name='standarditem_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.StandardItem'),
            preserve_default=False,
        ),
    ]
