# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('armour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armarmour',
            old_name='item',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='backpack',
            old_name='item',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='bodyarmour',
            old_name='item',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='headarmour',
            old_name='item',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='legarmour',
            old_name='item',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='armarmour',
            name='battle_item',
        ),
        migrations.AddField(
            model_name='armarmour',
            name='battle_items',
            field=models.ManyToManyField(blank=True, to='item.BattleItem'),
        ),
    ]
