# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armarmour',
            name='battle_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.BattleItem'),
        ),
    ]
