# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armour', '0002_auto_20160911_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armarmour',
            name='amount_of_items',
        ),
        migrations.RemoveField(
            model_name='armarmour',
            name='battle_items',
        ),
        migrations.RemoveField(
            model_name='armarmour',
            name='items',
        ),
        migrations.RemoveField(
            model_name='backpack',
            name='amount_of_items',
        ),
        migrations.RemoveField(
            model_name='backpack',
            name='items',
        ),
        migrations.RemoveField(
            model_name='bodyarmour',
            name='amount_of_items',
        ),
        migrations.RemoveField(
            model_name='bodyarmour',
            name='items',
        ),
        migrations.RemoveField(
            model_name='headarmour',
            name='amount_of_items',
        ),
        migrations.RemoveField(
            model_name='headarmour',
            name='items',
        ),
        migrations.RemoveField(
            model_name='legarmour',
            name='amount_of_items',
        ),
        migrations.RemoveField(
            model_name='legarmour',
            name='items',
        ),
    ]
