# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-20 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_simulator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combatrequest',
            name='initiating_hero',
        ),
        migrations.RemoveField(
            model_name='combatrequest',
            name='waiting_for_hero',
        ),
        migrations.AddField(
            model_name='combatrequest',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=999, null=True),
        ),
    ]
