# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-20 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_simulator', '0002_auto_20161120_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatrequest',
            name='combat_ready',
            field=models.BooleanField(default=False),
        ),
    ]
